// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp6HFQzHl1sKbR2QSlPaWOBMU5lMZR084',
    appId: '1:2389164304:web:498bf139fe91bf04462595',
    messagingSenderId: '2389164304',
    projectId: 'track-trek-a43ff',
    authDomain: 'track-trek-a43ff.firebaseapp.com',
    storageBucket: 'track-trek-a43ff.firebasestorage.app',
    measurementId: 'G-NDS38ZJT4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmbPS2x_oHcIUdn2V8nhG_nm_PbT29cDI',
    appId: '1:2389164304:android:fd3f63e8859f1bee462595',
    messagingSenderId: '2389164304',
    projectId: 'track-trek-a43ff',
    storageBucket: 'track-trek-a43ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgqIqEUBTmLNrOiXFtcT43AMegNVC0mAI',
    appId: '1:2389164304:ios:c99ff471a00a6a20462595',
    messagingSenderId: '2389164304',
    projectId: 'track-trek-a43ff',
    storageBucket: 'track-trek-a43ff.firebasestorage.app',
    iosBundleId: 'com.example.trackTrek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgqIqEUBTmLNrOiXFtcT43AMegNVC0mAI',
    appId: '1:2389164304:ios:c99ff471a00a6a20462595',
    messagingSenderId: '2389164304',
    projectId: 'track-trek-a43ff',
    storageBucket: 'track-trek-a43ff.firebasestorage.app',
    iosBundleId: 'com.example.trackTrek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp6HFQzHl1sKbR2QSlPaWOBMU5lMZR084',
    appId: '1:2389164304:web:dee981ca34b32734462595',
    messagingSenderId: '2389164304',
    projectId: 'track-trek-a43ff',
    authDomain: 'track-trek-a43ff.firebaseapp.com',
    storageBucket: 'track-trek-a43ff.firebasestorage.app',
    measurementId: 'G-JEJMJXQVCG',
  );
}
